# model
blocks: [2, 2, 2]
channels: [64, 128, 256]
stride: [1, 2, 2]
context_size: 128  # frames
dim: 256
depth: 3
num_heads: 4
bias: False
mlp_ratio: 2
dropout: 0.2
attn_dropout: 0.
# training
steps: 100000
eval_interval: 1000
batch_size: 32
learning_rate: 0.001
min_learning_rate: 0.0001
weight_decay: 0.1
warmup_steps: 100